### ISSUE TITLE
Can you please distribute a font file for this emoji. 

### ISSUE THREAD

**Issue by CosmicCodeBase** [microsoft/fluentui-emoji#92] opened 2023-02-22 03:03 UTC
Can you please distribute a font file for this emoji like Microsoft Segoe Emoji font.

**Comment by spencer-nelson** [comment] 2023-02-27 19:42
Thanks for your interest. This is a dupe of #16, so please follow that for any future updates.

**Closed by spencer-nelson** 2023-02-27 19:42 UTC

**Comment by CosmicCodeBase** [comment] 2023-02-28 04:34
Thanks and sorry for not checking earlier.
